name: Update Version and Build with Bun

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Bump version
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npm version patch --no-git-tag-version
          git add package.json package-lock.json || true
          git commit -m "ci: bump version [skip ci]" || echo "No changes to commit"
          git push || echo "No changes to push"

      - name: Install dependencies
        run: bun install

      - name: TypeScript build
        run: npx tsc


      - name: Bun compile (Linux)
        run: bun build --compile --target=linux-x64 dist/index.js --outfile=dist/moleport-linux

      - name: Bun compile (macOS)
        run: bun build --compile --target=macos-x64 dist/index.js --outfile=dist/moleport-macos || echo "macOS cross-compile not supported"

      - name: Bun compile (Windows)
        run: bun build --compile --target=windows-x64 dist/index.js --outfile=dist/moleport-win.exe || echo "Windows cross-compile not supported"

      - name: Upload binaries (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: moleport-binaries
          path: |
            dist/moleport-linux
            dist/moleport-macos
            dist/moleport-win.exe

      - name: Upload binaries to GitHub Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/moleport-linux
            dist/moleport-macos
            dist/moleport-win.exe
          body: |
            ## Release Notes
            - Automatically build and publish cross-platform binaries (Linux, macOS, Windows)
            - See commit history for detailed changes

            ### Downloads
            - [Linux](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/download/${GITHUB_REF_NAME}/moleport-linux)
            - [macOS](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/download/${GITHUB_REF_NAME}/moleport-macos)
            - [Windows](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/download/${GITHUB_REF_NAME}/moleport-win.exe)

            Please download the binary for your platform.
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
