name: Update Version and Build with Bun

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  update-version-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Bump version
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npm version patch --no-git-tag-version
          git add package.json package-lock.json || true
          git commit -m "ci: bump version [skip ci]" || echo "No changes to commit"
          git push || echo "No changes to push"

      - name: Install dependencies
        run: bun install

      - name: TypeScript build
        run: npx tsc

      - name: Build for macOS
        run: bun build dist/index.js --compile --outfile=dist/moleport-macos

      - name: Build for Linux
        run: bun build dist/index.js --compile --outfile=dist/moleport-linux --target=linux-x64

      - name: Build for Windows
        run: bun build dist/index.js --compile --outfile=dist/moleport-win.exe --target=windows-x64

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: moleport-binaries
          path: |
            dist/moleport-macos
            dist/moleport-linux
            dist/moleport-win.exe
